AWSTemplateFormatVersion: "2010-09-09"
Description: Elastic Container Registry Repository using Cloudformation

#------------------------
#   METADATA
#------------------------
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: ECR Configuration
        Parameters:
          - RepoNameParameter

#------------------------
#   PARAMETERS
#------------------------
Parameters:
  RepoNameParameter:
    Description: Name for ecr repo
    Type: String

#------------------------
#   RESOURCES
#------------------------
Resources:
  ecrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${RepoNameParameter}-repo
      ImageScanningConfiguration:
        ScanOnPush: true
